### ISSUE TITLE
Question about metric

### ISSUE THREAD

**Issue by yanqswhu** [crs4/SliceNet#2]
Thanks for your open-source work.

I looked into your codes and found out something that confused me.

In line  37 of `eval.py`, the RMSE is calculated without `sqrt` and `mask`.
I checked the definition of RMSE and didn't think it was correct.
```
    RMSE_linear = ((pred_depth - input_gt_depth) ** 2).mean()
```

Is there any particular reason why people use this formula as RMSE or just a typo?

**Comment by giannipint** [comment]
Thank you for finding the typo about sqrt, it probably happened during the cleanup of the code for the github release. as for the masking, the input data are assumed already masked
