### ISSUE TITLE
Why there needs gt_depth in inference.py?

### ISSUE THREAD

**Issue by therontau0054** [crs4/SliceNet#6]
I have the idea that the inference.py is to get the predicted depth of input image. But why there needs gt_depth?

**Comment by giannipint** [comment]
Mask is needed to be consistent with the results in the paper and with the methodology adopted on real acquisitions in the other compared works. In fact, in all these cases there is a mask of valid values that depends mainly on the acquisition instrument, where the upper and lower hemispheres of the acquisition field are missing and where ground truth values are considered reliable within a range of 16 meters. The results presented by our and other methods are obtained using this mask for training and testing. Doing the training without the mask yields equally consistent but scalar results that are not comparable.
